#!/usr/bin/env bash
#Install nginx web server

apt-get update
apt-get -y --allow-downgrades install nginx

mkdir /var/www/html && touch /var/www/html/index.html
echo "Hello World!" > /var/www/html/index.html
echo "server {
	listen	80 default_server;
	listen	[::]:80 default_server;
	add_header X-Served-By $HOSTNAME;
	root	/var/www/html;
	index	index.html index.htm;
    }" > /etc/nginx/sites-available/default

service nginx restart
