#!/usr/bin/env bash
#Install and automatically configures the nginx web server

apt-get update
apt-get -y --allow-downgrades install nginx

mkdir -p /var/www/html && touch /var/www/html/index.html
echo "Hello World!" > /var/www/html/index.html
touch /var/www/html/404.html
echo "Ceci n'est pas une page" > /var/www/html/404.html
echo "server {
	listen	80 default_server;
	listen	[::]:80 default_server;
	add_header X-Served-By $HOSTNAME;
	root	/var/www/html;
	index	index.html index.htm;
	location /redirect_me {
		return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;
        }
	error_page 404 /404.html;
	location /404 {
		internal;
	}
    }" > /etc/nginx/sites-available/default

service nginx restart