#!/usr/bin/env bash
# This script displays "Best School" 10 times, but for the 9th iteration,



i=0
while (( i<10 ))
do
	if [[ i -eq 9 ]]
	then
		printf "Hi\n"
	fi
	echo "Best School"
	(( i++ ))
done